### ISSUE TITLE
just want to clear the existing mediaBlobUrl how can i do that, is there any existing function for that?

### ISSUE THREAD

**Issue by siddhant-reactgeeks** [0x006F/react-media-recorder#11]

**Comment by 0x006F** [comment]
No, not at the moment. It gets replaced by the next recording and so on.

**Comment by siddhant-reactgeeks** [comment]
hello @0x006F  thanks for replying, so i have a send button on the UI on which i want to clear the video any idea how can we  do that?

**Comment by 0x006F** [comment]
Hey @siddhant-reactgeeks sorry for the delayed reply. You could unmount this component on a button click though. Although, it doesn't sound like a straightforward fix. The ideal way would be provide a function from this recorder that nullify the streams / blobs on demand. Let me check.

**Comment by jaydanurwin** [comment]
This would be great! I'm trying to find an easy way to remove the mediaBlobUrl as well and a built-in function would help make my code **much** cleaner

**Comment by siddhant-reactgeeks** [comment]
thanks @0x006F i am using this unmount fix for now, but it would be great if you could implement a callback for this.

**Comment by siddhant-reactgeeks** [comment]
https://e2ede998.ngrok.io/project/bBA2doHTR3nP39VJqmaH

**Comment by siddhant-reactgeeks** [comment]
https://5b32ce09.ngrok.io/project/vgIuJepfGjTm6HsjUsxl?recalc=true?view=true

**Comment by siddhant-reactgeeks** [comment]
https://5b32ce09.ngrok.io/project/5Vm4yWRNCmWrTvjtj8rj

**Comment by 0x006F** [comment]
Hey all, I'm sorry for the delayed response, but this has been fixed in latest release `V1.3.0`.  

Let me know

**Comment by realadamsmith** [comment]
Testing this now
