### ISSUE TITLE
Bug reports + Questions

### ISSUE THREAD

**Issue by wmik** [0x006F/react-media-recorder#12]
Followed a bug from a screen recording app and ended up here.
Think I've narrowed down the issue and possible fixes.

The main one is: ***Mic not disconnected after screen recording***.
- After a screen recording session stops for some reason the recording indicator is still active in the tab. This has happened on chrome so not sure about other browser.
https://github.com/0x006F/react-media-recorder/blob/e0838baf2c833ce0c8b7f3b4d6c3b9f3dd212ce4/src/index.ts#L211-L216

  Figured it might be the mic so I tried running 👇 inside ☝️
  ```js
  mediaStream.current.getTracks().forEach(track => track.stop())
  ```
  to disconnect the mic and it seemed to solve the issue.

[***`MediaStreamTrack.stop()`*** MDN Reference](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/stop)

The other one is: ***Incorrect default blob type format for screen recording video***.
- When the user enables the `screen` option without `video` i.e `screen=true`, `video=false`_(default)_ and does not provide a blobPropertyBag the type defaults to `audio/wav` which may not be ideal for video.
Happens 👇 
https://github.com/0x006F/react-media-recorder/blob/e0838baf2c833ce0c8b7f3b4d6c3b9f3dd212ce4/src/index.ts#L182-L184

  Another way to obtain defaults may be
  ```js
  let [sampleChunk] = mediaChunks.current; // <-- chunks are Blobs 🎉

  let blobProperty = Object.assign({ 
      type: sampleChunk.type
  }, blobPropertyBag); // <-- If that is undefined/null it uses the default
  // but it also accepts strings & arrays. 
  // Although it shouldn't matter that much since Blob will ignore unknown options anyway.
  ```
---

One question I have is when the component is mounted, it immediately requests for a media source. Is that the intended behavior? Are there downsides to letting the user control that? Maybe exposing the `getMediaStream` function? No?

Also I could be wrong but this feels a bit redundant
https://github.com/0x006F/react-media-recorder/blob/e0838baf2c833ce0c8b7f3b4d6c3b9f3dd212ce4/src/index.ts#L148-L154

Doubt the extra await step inside `loadStream` makes any difference since the enclosing function is invoked asynchronously at the top level _(inside `useEffect`)_, so calling `getMediaStream` directly _(inside `useEffect`)_ will have the same outcome but without the unnecessary extra function.

**Example test**
```js
function timeout(delay, result) { return new Promise(resolve => setTimeout(resolve, delay, result)); }

timeout(2000, 'done'); // <-- Promise {<pending>}
await timeout(2000, 'done'); // <-- Waits 2sec and prints 'done'

async function loadTimeout(...args) { return await timeout(...args); }

loadtimeout(2000, 'done'); // <-- Promise {<pending>} (No different from initial invocation of timeout without await)
await loadTimeout(2000, 'done'); // <-- Waits 2sec and prints 'done'

async function wait() { await timeout(2000, 'just wait'); }

wait(); // <-- Promise {<pending>} (also no different from initial invocation of timeout without await)
await wait(); // <-- Waits 2sec and prints undefined
```

Otherwise great stuff! 🎉 

Got inspired by this repo to roll out a _(shameless plug 😁)_ [hooks version](https://github.com/wmik/use-media-recorder) for fun and learn about the MediaRecorder API in the process.

It does have its challenges e.g. trying to figure out how to disconnect all connected media sources (camera/mic) when a component is no longer mounted and also compose tests.
Any feedback is welcome 🙂 Cheers.

**Comment by 0x006F** [comment]
@wmik Thanks for taking this much time to carefully isolate these small issues.  

> ```mediaStream.current.getTracks().forEach(track => track.stop())```   

I swear I had this stop call for every tracks (back when I was experimenting). But I don't recall why it didn't make it to the repo. Let me double check this one more time. Is it working for you in your fork?

> The other one is: Incorrect default blob type format for screen recording video.  

Fantastic catch! (and thanks for the solution though)  

> when the component is mounted, it immediately requests for a media source. Is that the intended behavior?  

Kinda. We could expose the `getMediaStream` to the user, but I thought, if we're gonna mount a component that asks for a video / audio (no matter what the recording state) we should let the end-user know about these device access. :grin: 

> Doubt the extra await step inside loadStream makes any difference  

Yeah, it won't make any difference. I just copy-pasted some of the old code blocks while migrating this project to react hooks. Need to remove that.  

> Got inspired by this repo.  

You just made my day!. You've no idea how much happy I'm to hear this. I know, this library isn't perfect, but it so happy to know that this library helped / inspired someone. 

Although, I must apologize for this delay to respond. I've got a bit busy for the past few weeks at my full-time.
