### ISSUE TITLE
How can we get chunk blob, is there any props around this ?

### ISSUE THREAD

**Issue by raj-reactgeeks** [0x006F/react-media-recorder#13]
I want to get blob in a chunk, I have checked existing props I just found previewStream to get the current stream but I need a blob so that I can send it to server and store in real-time.

ondataavailable  method is available to get blob in a chunk, So can you please add chunk blob props support as well.

  mediaRecorder.ondataavailable = function (e: any) {
            console.log("blob =  ", e.data)
});

**Comment by wmik** [comment]
Duplicate of #8

**Comment by 0x006F** [comment]
@raj-reactgeeks landed in `v1.2.1`
