### ISSUE TITLE
How can I record the screen and my camera at the same time? 

### ISSUE THREAD

**Issue by MichaelJC91** [0x006F/react-media-recorder#21]
I want to record my screen and webcam at the same time and have my webcam stream be constraint to a 200x200 square in the bottom left corner.

How could I achieve this?

**Comment by brentcappello** [comment]
Yes, this is achievable.

You can use the `previewStream` as mentioned in the docs here: https://github.com/0x006F/react-media-recorder#previewstream

Here is an additional example:
``` js
 const VideoPreview = () => {
    const videoRef = useRef(null);

    useEffect(() => {
      navigator.mediaDevices
        .getUserMedia({ video: true })
        .then(function (stream) {
          videoRef.current && (videoRef.current.srcObject = stream);
        });
    });
    return <video ref={videoRef} width={200} height={200} autoPlay />;
  };
```

Hope that helps.

**Comment by HBM08** [comment]
> Yes, this is achievable.
> 
> You can use the `previewStream` as mentioned in the docs here: https://github.com/0x006F/react-media-recorder#previewstream
> 
> Here is an additional example:
> 
> ```js
>  const VideoPreview = () => {
>     const videoRef = useRef(null);
> 
>     useEffect(() => {
>       navigator.mediaDevices
>         .getUserMedia({ video: true })
>         .then(function (stream) {
>           videoRef.current && (videoRef.current.srcObject = stream);
>         });
>     });
>     return <video ref={videoRef} width={200} height={200} autoPlay />;
>   };
> ```
> 
> Hope that helps.

Video preview works indeed, but did somebody tried audio recording preview ?
It looks like the autoplay doesn't work so you don't get any feedback as you record ...
