### ISSUE TITLE
Audio file can't be played in safari

### ISSUE THREAD

**Issue by seonghyeonkimm** [0x006F/react-media-recorder#32]
### Descriptions
- Made the audio file in chrome browser using this library
- Uploaded the file to firebase and played it in the browser. chrome play it well. But it is not played well on safari

I don't have any clue about this problem. Is there anyone who can help me to solve this problem?

**Comment by robertjwozniak** [comment]
@seonghyeonkimm It seems to be an issue with the .ogg audio format. Did your audio get saved in Ogg format? If yes, then Safari does not support that.

**Comment by tsejerome** [comment]
On every file upload, transcode it to . For my case, I am using https://aws.amazon.com/elastictranscoder/ to transform every file upload from client side into a mp3 so that all browsers can play.

Took our team like a whole week for this

**Comment by seonghyeonkimm** [comment]
@robertjwozniak @tsejerome Thanks for your help. I will try to transcode it.

**Comment by eli-s-r** [comment]
Is there any way to do this client-side without using a large package such as https://github.com/Kagami/ffmpeg.js? We need to support immediate playback of recordings in the browser, _before_ the contents are sent to the server.

**Comment by no-1ne** [comment]
https://github.com/ai/audio-recorder-polyfill
https://github.com/zhuker/lamejs
 do it on the browser side, 
although LGPL as per my understanding, isnt as straightforward as mentioned in the LICENSE below https://github.com/zhuker/lamejs/blob/master/LICENSE
