### ISSUE TITLE
Video gets flipped in preview

### ISSUE THREAD

**Issue by dolly-kumar** [0x006F/react-media-recorder#35]
Hi,

1. While recording I need it to be like a mirror.
2. After recording, it must play exactly what I recorded and not flip just like we have normally in our smartphones while making videos.

**Comment by 0x006F** [comment]
You could try flipping the `<video/>` element with CSS  

```css
transform: rotateY(180deg);  
```

**Comment by ayushidianapps** [comment]
@dolly-kumar was your issue resolved as this has been marked as done?
I am still facing the same issue, the recorder video is flipped
