### ISSUE TITLE
Is not recording the audio of the video that I am playing on my screen

### ISSUE THREAD

**Issue by PedroHenrike20** [0x006F/react-media-recorder#47]
Hi,
I am developing a service to make video calls and record the user screen with this component. I am trying to record the user screen on a page with an Agora.io call, that is a service that runs on top of RTC Stream to allow video calls between clients. 
I've succeeded to record my screen with my microphone audio and webcam video, and the video coming from the stream as part of my screen. But the resulting blob comes with no audio coming from the screen, only my microphone audio. There are something that i am doing wrong? i want to record both my mic audio and the video call audio. Is it Possible? Heres my code.

<ReactMediaRecorder screen={true} blobPropertyBag={{type: "video/mp4" }}  render={({status, startRecording, stopRecording, mediaBlobUrl,  pauseRecording, resumeRecording}) => (
        <div className="wrapper meeting">
        <div className="ag-header">

             <div className="ag-header-msg">
               <div style={{width: "45%" }}>
                 <p style={{color: "#FFF"}}>

                  Room:&nbsp;<span id="room-name">{channel}</span>
                 </p>

               </div>

               <div style={{width: "50%", display: 'flex', justifyContent: 'space-between'}}>
                 <div style={{display: 'flex', justifyItems: 'center', alignItems: 'center', width: 75}}>

         
              
             </div>
           </div>
           <div className="ag-main">
             <div className="ag-container">
               <AgoraVideoCall
                videoProfile={videoProfile}
                channel={channel}
                transcode={transcode}
                attendeeMode={attendeeMode}
                baseMode={baseMode}
                appId={appId}
                uid={uid}
                
              />
            {/* <video src={mediaBlobUrl} controls autoPlay loop /> */}
            </div>
          </div>
      </div>
      )}
      />

**Comment by 0x006F** [comment]
AFAIK, the `getUserMedia` doesn't give the _speakers_ (since it's an output device) info. You'll need to do some loopback (from the speakers to the input device) in the OS level to get this working.

**Comment by PedroHenrike20** [comment]
Do you have a path for me to follow?

**Comment by Amir-Pourhadi** [comment]
I have this problem :(
Did you find any solution for it?

**Comment by PedroHenrike20** [comment]
Hello, I was able to solve this issue by opening a new browser window with the recording component on it, then he was able to record the audios that make up the call and also the browser window.

Example: 

```
function OpenLink(strDestination) {
    var features = [
      "left=450",
      "top=10",
      "location=0",
      "menubar=0",
      "resizable=0",
      "scrollbars=0",
      "status=0",
      "titlebar=0",
      "toolbar=0",
      "width=615",
      "height=485",
    ];
    setIsRecording(true);

    var win = window.open(strDestination, "windowOpenTab", features.join(","));

    win.addEventListener("DOMContentLoaded", function() {
      var pu_width = win.outerWidth;
      var pu_height = win.outerHeight;
      win.onresize = function() {
        win.resizeTo(pu_width, pu_height);
        win.focus();
      };
    });

    var winClosed = setInterval(function() {
      if (win.closed) {
        clearInterval(winClosed);
        setIsRecording(false);
        alert(
          "Sua gravação foi encerrada! Esperamos que já tenha realizado o download do arquivo.",
        );
      }
    }, 250);
  }
```
