### ISSUE TITLE
clearBlobUrl() method should also call URL.revokeObjectURL()

### ISSUE THREAD

**Issue by briangershon** [0x006F/react-media-recorder#64]
From https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL they mention call `revokeObjectURL` method when you've finished using an object URL to let the browser know not to keep the reference to the file any longer.

**Comment by briangershon** [comment]
Thank you @0x006F for adding this! I was in the middle of a hackday event, so didn't have a change to submit a PR myself.

Also, I ended up adding one more line to `clearBlobUrl()` to reset the workflow back to `idle` as well: [Line 207](https://github.com/BryceHaley/team7-blackfoot-chat-app/blob/main/frontend/src/lib/ReactMediaRecorder.js#L207)

(I had to fork your code into a new file due to #63 but a reference to your project at the top of the file)

If you don't get around to, I can work on a PR.

**Comment by 0x006F** [comment]
@briangershon thanks! I appreciate your help. 😊

**Comment by briangershon** [comment]
No worries, I'll work on that PR!

Thanks again, this component was the only way we were able to get our recording feature up and running in a short amount of time.

**Comment by 0x006F** [comment]
Glad that this helped!
