### ISSUE TITLE
Maximum 10min video recording validation

### ISSUE THREAD

**Issue by namitamehta** [0x006F/react-media-recorder#77]
Hi
I'm developing a video recording functionality in our website, I have to add validations, maximum video recording should be 10min after that it should automatically stop recording. So can anybody help me in achieving this.

Looking forward to hearing from you soon!

Thanks!

**Comment by tylerzey** [comment]
https://github.com/bradgarropy/use-countdown 

You could just use a hook like this and then call the stopRecording method from `react-media-recorder` upon the 10 min being completed.

If you expose pause/resume, make sure to pause & resume your timer.

**Comment by namitamehta** [comment]
> https://github.com/bradgarropy/use-countdown
> 
> You could just use a hook like this and then call the stopRecording method from `react-media-recorder` upon the 10 min being completed.
> 
> If you expose pause/resume, make sure to pause & resume your timer.

**Comment by namitamehta** [comment]
> https://github.com/bradgarropy/use-countdown
> 
> You could just use a hook like this and then call the stopRecording method from `react-media-recorder` upon the 10 min being completed.
> 
> If you expose pause/resume, make sure to pause & resume your timer.

Thanks @tylerzey it was helpful

**Comment by namitamehta** [comment]
Closing the issue, as i have used currentTime property of video tag to validate recording time.
Thanks!
