### ISSUE TITLE
Can you add the function the get the Blob object?

### ISSUE THREAD

**Issue by christopherABM** [0x006F/react-media-recorder#8]
Hi dude, I was using trying to implement your library but in my app i need the Blob object, can you do something like 

> <ReactMediaRecorder
>                       video
>                       render={({ status, startRecording, stopRecording, mediaBlobUrl, **blobObject**, previewStream }) => {
>             //.... my code
}}
                    />
>

**Comment by 0x006F** [comment]
Hey man, sorry for the delay. Had to do some other works :D  

Well, it's easy to emit the blob object, but may I know what's the use case here? Just being curious.

**Comment by christopherABM** [comment]
Hi dude, I was recording videos and trying to upload the file to server, to do that I was making a fetch  to get the blob object and converted to  a file using this :

```
blob = await fetch(blobUrl).then(r => {
        return r.blob();
      });
video = new File([blob], "video", { type: blob.type });
```

But for some reason only chrome was falling, when I was making the fetch I got this error  ERROR_INVALID_HANDLE, I also tried with XMLHttpRequest and nothing 
So I thought It would be a good option to have the blob Object just in case jeje, because
the funny part of this history is that I just needed to restart my pc and now It works perfectly

**Comment by 0x006F** [comment]
So..., I guess, the issue is resolved then? 😬

**Comment by harshzalavadiya** [comment]
Hi @0x006F, 

fetch solution works but having blob passed as second arguement on `onStop` might be nice thing as you already have a blob available 🙂

#### proposed change

https://github.com/0x006F/react-media-recorder/blob/master/src/index.ts#L188

```diff
- onStop(url);
+ onStop(url, blob);
```

**Comment by christopherABM** [comment]
Hi @harshzalavadiya what I did was this:
 ```
if (status === 'stopped' && blob) {
      blob = await fetch(blob).then(r => {
        return r.blob();
      }).catch(e => console.log(e));
      this.video = new File([blob], "video", { type: blob.type });
    }
```
I hope that helps you

**Comment by 0x006F** [comment]
Thanks @christopherABM / @harshzalavadiya this has been asked by multiple times, and I'm sorry for the delay. This is landed in `V1.2.1`

**Comment by nobleach** [comment]
I'm confused on how one would use the `onStop` prop when using the hooks that are provided. That seems to be a good solution only if using the `<ReactMediaRecorder />` component.

**Comment by khalidahmed10p** [comment]
@nobleach did you get the solution for this?

**Comment by nobleach** [comment]
I did not. I ended up building a component by hand.
