### ISSUE TITLE
how can i get the stream as a  blob after i have stopped sharing my screen.

### ISSUE THREAD

**Issue by siddhant-reactgeeks** [0x006F/react-media-recorder#9]

**Comment by 0x006F** [comment]
Hey @siddhant-reactgeeks as its design, it won't give you the actual `blob` object, just the `url`. Not that it's difficult, but why the need for `blob`?

**Comment by gvnramu** [comment]
Hi @0x006F I had the same problem and I need to upload the recorded file to the server. Please help me out

**Comment by siddhant-reactgeeks** [comment]
hello @0x006F  and @gvnramu you guys just need to do this:
`  const blob = await fetch(mediaBlobUrl).then((r) => r.blob());`

this will give you the blob for the video which you can upload easily

**Comment by siddhant-reactgeeks** [comment]
> Hey @siddhant-reactgeeks as its design, it won't give you the actual `blob` object, just the `url`. Not that it's difficult, but why the need for `blob`?

hello there just wanted to upload that video that's why
