### ISSUE TITLE
Compatibility with Next.js in 1.6.6

### ISSUE THREAD

**Issue by dvdokkum** [0x006F/react-media-recorder#98]
I'm getting this error when putting a basic demo together:

```Error: There is already an encoder stored which handles exactly the same mime types.```

A quick search showed that it may be related to Extendable-Media-Recorder(?), which looks like it was just added by @PipesNBottles. I rolled my version back down to `1.6.5` and the error went away. 

If there's any additional detail I can provide to help debug please let me know!

**Comment by PipesNBottles** [comment]
how are you rendering the component? In my test cases I was rendering only one component per page and I can quickly add extra logic to make sure only one encoder is ever stored

**Comment by dvdokkum** [comment]
Here's a gist: https://gist.github.com/dvdokkum/d1078da347458f9998ab7baa9d713f73

`record.js` is the component and `record-test.js` is the parent page.

AFAIK I'm only loading it once. Not sure if relevant, but this is a next.js app.

**Comment by PipesNBottles** [comment]
So I looked into it and I can suppress the message though I'd rather not do that. Currently looking into the extendable recorder it appears like a nice feature to have to free up memory in the browser, a feature the native API doesn't support. I also tested with rendering two recorders at the same time for 3 min and I didn't find any noticeable difference in the files being recorded in their binaries (both were WAV 16-bit encoded) sound wise they were the same to me but I'm not an audiophile. Likewise I was also able to get two different `blobUrls` with the two different recordings. If necessary I can wrap it in a warning.

**Comment by dvdokkum** [comment]
Sorry I'm not sure I understand. How do you suggest handling the runtime error? When I put the return block in a try/catch I just get a reference error on `Blob`. Is something in my code rendering the component twice? I tried to stick as close to the demo code in the readme as possible, which works in `1.6.5` but throws errors in `1.6.6`. Appreciate your help on this!

**Comment by dvdokkum** [comment]
I've been trying to debug this further and need to give it a rest for a bit, but I'm going leave what I've got so far in case anyone else is having these issues. In short, I think the Extendable-Media-Recorder dep is breaking off the shelf compatibility with Next js.

1. I was able to fix the parent issue with multiple encoders being called. This is happening because `create-next-app` defaults `reactStrictMode` to `true` in `next.config.js`. Strict mode will call all components twice, which makes Extendable-Media-Recorder throw this error. If you turn off StrictMode this error goes away, but a new error emerges!

2. You'll start getting `Reference Error: Blob is not defined`. This is another new issue with `1.6.6` that is not present in `1.6.5` and I think is specific to Next because of the way it does server side rendering. In order to get around this, you'll need to [Dynamically Import](https://nextjs.org/docs/advanced-features/dynamic-import) the component that is using `react-media-recorder` like so:

```const Recorder = dynamic(() => import('./record'))```

That gets everything working in dev again, but now the problem I have yet to solve, running in prod! 

3. `npm run build` now crashes on another `ReferenceError` for `Blob`:

```
> Build error occurred
ReferenceError: Blob is not defined
    at /Users/dvd/olivefm/node_modules/media-encoder-host/build/es5/bundle.js:10:13
    at /Users/dvd/olivefm/node_modules/media-encoder-host/build/es5/bundle.js:2:65
    at Object.<anonymous> (/Users/dvd/olivefm/node_modules/media-encoder-host/build/es5/bundle.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/dvd/olivefm/node_modules/extendable-media-recorder/build/es5/bundle.js:2:176 {
  type: 'ReferenceError'
}```

If anyone has ideas on how to get around this, I'm all ears.

**Comment by dvnrsn** [comment]
Forgive my ignorance. Is there no way to avoid running on server? Seems like next should have a means to skip server side running. This can't be the first time someone has needed to use a browser api that is not available in node?

**Comment by dvdokkum** [comment]
> This can't be the first time someone has needed to use a browser api that is not available in node?

Yeah, I mean before the extendable-media-recorder dep was added it worked fine, and the base library uses the mediaRecorder browser API, so perhaps it is just something in the implementation which is causing the issue.

**Comment by dvdokkum** [comment]
Hate to bug, but any ideas on how to get this working @PipesNBottles @0x006F? I'd love to be able to use the new wav functionality, and I feel like I'm almost there but I just get this pesky reference error on `Blob` when trying to do a production build coming from extendable-media-recorder. I'm not super well versed in frontend dependency land, and I'm assuming there's something simple that I can do (perhaps in webpack?) to get around this problem. I haven't been able to find a clear answer elsewhere.

**Comment by Szuszi** [comment]
@dvdokkum I came across the same issue as you did by having the `Error: There is already an encoder stored which handles exactly the same mime types`. I managed to use this version, by copy-ing the whole code and by applying a try-catch functionality to the initialization useEffect of the component (`await register(await connect());`). If you only had this error, you can catch it so it doesn't crash your application. My experience was that the recorder could be still used perfectly, even if this is a dirty hack to solve this. I used Next.js as you did and I managed to record screens with this.

**Comment by maxIrvine** [comment]
Hi, everyone! I am also encountering the same issue... if you come up with a workaround I would love to hear it!

**Comment by dvdokkum** [comment]
I've got all of this sorted out now, so if you are just finding this thread and trying to get things working in Next try the following:

> 1. I was able to fix the parent issue with multiple encoders being called. This is happening because `create-next-app` defaults `reactStrictMode` to `true` in `next.config.js`. Strict mode will call all components twice, which makes Extendable-Media-Recorder throw this error. If you turn off StrictMode this error goes away, but a new error emerges!
> 2. You'll start getting `Reference Error: Blob is not defined`. This is another new issue with `1.6.6` that is not present in `1.6.5`. I think the way Next does server side rendering is not playing nice with extendable-media-recorder. In order to get around this, you'll need to [Dynamically Import](https://nextjs.org/docs/advanced-features/dynamic-import) the component that is using `react-media-recorder` like so:
> 
> `const Recorder = dynamic(() => import('./record'))`

**Comment by rsweetland** [comment]
To clarify using the readme example, it would look something like this...

```javascript
// record.jsx
import { useReactMediaRecorder } from "react-media-recorder";

const RecordView = () => {
  const { status, startRecording, stopRecording, mediaBlobUrl } =
    useReactMediaRecorder({ video: true });

  return (
    <div>
      <p>{status}</p>
      <button onClick={startRecording}>Start Recording</button>
      <button onClick={stopRecording}>Stop Recording</button>
      <video src={mediaBlobUrl} controls autoPlay loop />
    </div>
  );
};
```


```javascript
// index.jsx (or container or whatever)
const Recorder = dynamic(() => import('./record'))
```

**Comment by jasondainter** [comment]
I'm having this issue also. I get:

```
Error: There is already an encoder stored which handles exactly the same mime types.
Call Stack
Worker.eval
node_modules/broker-factory/build/es2019/module.js (33:0)
```

In NextJS and when trying to load the react-video-recorder inside a collapsible menu (react spring).

For some reason turning strict mode off didnt help (and I dont really want to do that anyhow).

Any updates since last time, if not does anyone have any tips how I can supress that error?
